version: "3.8"
services:
  nginx:
    ports:
      - '80:80'
    depends_on:
      - gunicorn
    volumes:
      - ./src/:/home/app/
    build:
      context: ./
      dockerfile: ./infrastructure/nginx.Dockerfile
  gunicorn:
    build:
      context: ./
      dockerfile: ./infrastructure/gunicorn.Dockerfile
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./src/:/home/app/
    ports:
      - '8000:8000'